---
version: "3"

services:
  mysql:
    image: mysql:5.7
    networks:
      - church-people-backend
    volumes:
      - church-people-data:/var/lib/mysql
    ports:
        - "3307:3306"
    environment:
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "churchpeople"

  church-people:
    depends_on:
      - mysql
    image: churchsource/church-people
    #build:
    #  context: .
    #  dockerfile: ./Dockerfile
    networks:
      - church-people-backend
    ports:
      - "8081:8080"
    environment:
      SPRING_DATABASE_HOST: "mysql"
      SPRING_DATABASE_PORT: "3306"

  church-people-frontend:
    image: churchsource/cp-frontend
    networks:
      - church-people-backend
    ports:
      - "4000:81"

networks:
  church-people-backend:
  church-people:
    external:
      name: church-people

volumes:
  church-people-data:
