---
version: "3"

services:
  mysql:
    image: mysql:5.7
    networks:
      - church-people-backend
    volumes:
      - church-people-data:/var/lib/mysql
    ports:
        - "3307:3306"
    environment:
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "churchpeople"

  church-people:
    depends_on:
      - mysql
    image: churchsource/church-people
#    build:
#      context: .
#      dockerfile: ./Dockerfile
    networks:
      - church-people-backend
    ports:
      - "8082:8080"
    environment:
      SPRING_DATABASE_HOST: "mysql"
      SPRING_DATABASE_PORT: "3306"

  church-gateway:
    depends_on:
      - church-people
    image: churchsource/church-gateway
#    build:
#      context: .
#      dockerfile: ./Dockerfile
    networks:
      - church-people-backend
    ports:
      - "80:80"
    environment:
      GATEWAY_PORT: "80"
      PEOPLE_HOST: "church-people"
      PEOPLE_PORT: "8080"
      SONG_HOST: "localhost"
      SONG_PORT: "9000"
      SITE_HOST:  "church-people-frontend"
      SITE_PORT:  "81"
      SHEET_HOST: "mvsongs.co.za"
      SHEET_PORT: "8000"

  church-people-frontend:
    image: churchsource/cp-frontend
    networks:
      - church-people-backend
    ports:
      - "4000:81"
    environment:
      REACT_APP_API_PORT: "80"
      REACT_APP_API_URL: "mvsongs.co.za"

networks:
  church-people-backend:
  church-people:
    external:
      name: church-people

volumes:
  church-people-data:
